QUESTION_BANK = [
    {"id": "R1", "category": "Realistic", "text": "I enjoy working with tools, machines, or physical systems."},
    {"id": "R2", "category": "Realistic", "text": "I like solving hands-on technical problems."},
    {"id": "R3", "category": "Realistic", "text": "I feel comfortable building, repairing, or testing things."},
    {"id": "R4", "category": "Realistic", "text": "I prefer practical tasks over abstract discussions."},
    {"id": "R5", "category": "Realistic", "text": "I would enjoy working on real-world systems and operations."},
    {"id": "I1", "category": "Investigative", "text": "I enjoy analyzing data to discover patterns."},
    {"id": "I2", "category": "Investigative", "text": "I like asking questions and researching answers deeply."},
    {"id": "I3", "category": "Investigative", "text": "I enjoy solving complex logical or scientific problems."},
    {"id": "I4", "category": "Investigative", "text": "I feel motivated by understanding how things work."},
    {"id": "I5", "category": "Investigative", "text": "I would enjoy work that requires observation and critical thinking."},
    {"id": "A1", "category": "Artistic", "text": "I like expressing ideas in original or creative ways."},
    {"id": "A2", "category": "Artistic", "text": "I enjoy designing, writing, or creating content."},
    {"id": "A3", "category": "Artistic", "text": "I prefer open-ended tasks where I can experiment."},
    {"id": "A4", "category": "Artistic", "text": "I often think about how to improve the look or feel of things."},
    {"id": "A5", "category": "Artistic", "text": "I enjoy activities that involve imagination and originality."},
    {"id": "S1", "category": "Social", "text": "I enjoy helping people solve their problems."},
    {"id": "S2", "category": "Social", "text": "I feel energized when guiding or mentoring others."},
    {"id": "S3", "category": "Social", "text": "I like working in teams and supporting collaboration."},
    {"id": "S4", "category": "Social", "text": "I care about making a positive impact on people."},
    {"id": "S5", "category": "Social", "text": "I would enjoy roles that involve teaching, counseling, or service."},
    {"id": "E1", "category": "Enterprising", "text": "I enjoy leading people toward a goal."},
    {"id": "E2", "category": "Enterprising", "text": "I like persuading others with ideas or plans."},
    {"id": "E3", "category": "Enterprising", "text": "I feel comfortable taking initiative in uncertain situations."},
    {"id": "E4", "category": "Enterprising", "text": "I would enjoy business, strategy, or decision-making roles."},
    {"id": "E5", "category": "Enterprising", "text": "I am motivated by growth, achievement, and influence."},
    {"id": "C1", "category": "Conventional", "text": "I like organizing information carefully and accurately."},
    {"id": "C2", "category": "Conventional", "text": "I feel comfortable following structured processes."},
    {"id": "C3", "category": "Conventional", "text": "I enjoy planning, scheduling, and keeping things orderly."},
    {"id": "C4", "category": "Conventional", "text": "I prefer clarity, rules, and reliable systems."},
    {"id": "C5", "category": "Conventional", "text": "I would enjoy roles that involve records, analysis, or coordination."},
]

LIKERT_OPTIONS = {
    1: "Strongly Disagree",
    2: "Disagree",
    3: "Neutral",
    4: "Agree",
    5: "Strongly Agree",
}
